name: tomo-env
channels:
  - conda-forge
  - astra-toolbox
dependencies:
  - python
  - ipywidgets
  - astra-toolbox
  - h5py
  - numpy
  - matplotlib
  - scikit-image=0.17.2
  - tomopy
  - pyvista
  - pyevtk
  - scipy
  - pip
  - watermark
  - pip:
    - opencv-python-headless
