name: tomo-env
channels:
  - conda-forge
  - astra-toolbox
dependencies:
  - python==3.7
  - ipywidgets==7.6.5
  - astra==2.0.0
  - cv2==4.5.1
  - h5py==3.6.0
  - numpy==1.17.0
  - matplotlib==3.4.3
  - skimage==0.18.1
  - tomopy==1.7.1
  - pyvista==0.33.3
  - pyevtk==1.2.0
  - scipy==1.1.0
